### ISSUE TITLE
question Collection

### ISSUE THREAD

**Issue by HoseinRezaeeM** [HoseinRezaeeM/DigiWallet_functional-interface#21]
class MyIterable implements Iterable<Integer>{
Collection<Character> val;
public MyIterable(Collection<Character> val) { this.val = val; }
@Override
public Iterator<Integer> iterator() {
return Arrays.asList(1,2,3,3,4).iterator();
}
}
public class MyProgram{
public static void main(String[] args) {
for (Object o : new MyIterable(Arrays.asList('A', 'A', 'B')))
System.out.print(o);
}
}

**Comment by SinaRahimii75** [comment]
very good what answer?

**Comment by HoseinRezaeeM** [comment]
Answer 12334 
because second itrerator Invalid

**Comment by SinaRahimii75** [comment]
oh thanks
